server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repair_agency
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect