server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repair-agency
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-ui

domelian:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000